version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glyphnet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  glyphnet_api_node:
    build: .
    command: uvicorn glyphnet_ultimate_v2.federation.api:app --host 0.0.0.0 --port 8000
    environment:
      - GLYPHNET_DATABASE_URL=postgresql://user:password@postgres_db/glyphnet_db
      - NATS_URL=nats://nats:4222
    ports:
      - "8000:8000"
    depends_on:
      - nats
      - postgres_db
  glyphnet_resonator_node:
    build: .
    command: python -m glyphnet_ultimate_v2.federation.resonator_worker
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
volumes:
  postgres_data:
