id: injector_graphene_materials
title: "Audit matériaux 2D (graphène) — L2C"
version: "0.1.0"
metadata:
  purpose: "Tracer pipelines de simulation et caractérisation de matériaux 2D"
pipeline:
  - capability: core.loader
    params: { path: "workspace/graphene", entry_point: "graphene.py" }
  - capability: glyphnet.instrumentation
    params: { mode: "python_augmented", glyphs: ["⟦Audit:Graphene⟧","⟦CORE:ΔM11.3⟧"] }
  - capability: tests.property_based
    params: { module: "tests/test_graphene.py" }
  - capability: governance.trust_report
    params: { sign_with: "KeyGuardian" }
outputs:
  - name: trust_report
    path: "./outputs/graphene_trust.json"
