id: injector_biophysics_interfaces
title: "Audit interfaces bio/physique — L2C"
version: "0.1.0"
metadata:
  purpose: "Tracer pipelines Python pour biomolécules dans matrices physiques"
pipeline:
  - capability: core.loader
    params: { path: "workspace/biophysics", entry_point: "bio_interface.py" }
  - capability: glyphnet.instrumentation
    params: { mode: "python_augmented", glyphs: ["⟦Audit:BioInterface⟧","⟦CORE:ΔM11.3⟧"] }
  - capability: tests.mutation
    params: { threshold: 80 }
  - capability: governance.trust_report
    params: { sign_with: "KeyGuardian" }
outputs:
  - name: trust_report
    path: "./outputs/biophysics_trust.json"
