id: injector_nanostructures_spectroscopy
title: "Audit nanostructures et spectroscopie — L2C"
version: "0.1.0"
metadata:
  purpose: "Tracer pipelines spectroscopiques (Raman, IR, XPS) de nanostructures"
pipeline:
  - capability: core.loader
    params: { path: "workspace/nanostructures", entry_point: "spectro.py" }
  - capability: glyphnet.instrumentation
    params: { mode: "python_augmented", glyphs: ["⟦Audit:NanoSpectro⟧","⟦CORE:ΔM11.3⟧"] }
  - capability: tests.property_based
    params: { module: "tests/test_spectro.py" }
  - capability: governance.trust_report
    params: { sign_with: "KeyGuardian" }
outputs:
  - name: trust_report
    path: "./outputs/nanospectro_trust.json"
